 export const LIST_PROVINCE=[
    {
        MA:67,
        NAME:"An Giang",
    },{ MA:72,NAME:"Bà Rịa - Vũng Tàu"},
    {MA:94,NAME:"Bạc Liêu"},
    {MA:1,NAME:"Bắc Kạn"},
    {MA:1,NAME:"Bắc Giang"},{MA:1,NAME:"Bắc Ninh"},
    {MA:71,NAME:"Bến Tre"},
    {MA:61,NAME:"Bình Dương"},
    {MA:77,NAME:"Bình Định"},
    {MA:93,NAME:"Bình Phước"},
    {MA:86,NAME:"Bình Thuận"},{ MA:69,NAME:"Cà Mau"},
    {MA:1,NAME:"Cao Bằng"},
    {MA:65,NAME:"Cần Thơ"},
    {MA:43,NAME: "Đà Nẵng"}, {MA:47,NAME:"Đắk Lắk"},
    {MA:48,NAME:"Đắk Nông"}, {MA:60,NAME:"Đồng Nai"},
    {MA:66,NAME:"Đồng Tháp"},{ MA:1,NAME:"Điện Biên"},
    {MA:81,NAME:"Gia Lai"},
    {MA:0,NAME:"Hà Giang"},
    {MA:0,NAME:"Hà Nam"}, {MA:29,NAME:"Hà Nội"},
    {MA:38,NAME: "Hà Tĩnh"},
    {MA:0,NAME:"Hải Dương"},{MA:1,NAME:"Hải Phòng"},
    {MA:1,NAME:"Hòa Bình"}, {MA:95,NAME:"Hậu Giang"},
    {MA:1,NAME:"Hưng Yên"}, {MA:59,NAME:"Thành phố Hồ Chí Minh"},
    {MA:79,NAME:"Khánh Hòa"}, {MA:68,NAME:"Kiên Giang"},
    {MA:82,NAME:"Kon Tum"},
    {MA:1,NAME:"Lai Châu"}, {MA:1,NAME:"Lào Cai"},
    {MA:1,NAME:"Lạng Sơn"},
    {MA:49,NAME:"Lâm Đồng"}, {MA:62,NAME:"Long An"},
    {MA:1,NAME:"Nam Định"}, {MA:37,NAME:"Nghệ An"},
    {MA:35,NAME:"Ninh Bình"},
    {MA:85,NAME: "Ninh Thuận"}, {MA:1,NAME:"Phú Thọ"},
    {MA:78,NAME:"Phú Yên"},
    {MA:73,NAME:"Quảng Bình"},
    {MA:92,NAME:"Quảng Nam"},
    {MA:76,NAME:"Quảng Ngãi"},
    {MA:1,NAME:"Quảng Ninh"},
    {MA:74,NAME:"Quảng Trị"},
    {MA:83,NAME: "Sóc Trăng"},{MA:1,NAME: "Sơn La"},
    {MA:70,NAME:"Tây Ninh"},
    {MA:1,NAME:"Thái Bình"},
    {MA:1,NAME:"Thái Nguyên"},{MA:36,NAME: "Thanh Hóa"},
    {MA:75,NAME:"Thừa Thiên - Huế"}, {MA:63,NAME:"Tiền Giang"},
    {MA:84,NAME:"Trà Vinh"},
    {MA:1,NAME:"Tuyên Quang"},
    {MA:64,NAME:"Vĩnh Long"},
    {MA:1,NAME:"Vĩnh Phúc"}, {MA:1,NAME:"Yên Bái"}
]
